server:
  port: 8888

amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    accesskey: key
    secretkey: secret

kafka:
  config:
    bootstrap-servers: http://localhost:9092
    schema-registry-url: http://localhost:8081
    group-id: foo